# Generated by Django 3.1.1 on 2021-03-13 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('general', '0006_auto_20201018_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='EP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sign_up', models.DateTimeField()),
                ('applications_count', models.IntegerField(default=0)),
                ('contacted_at', models.DateTimeField()),
                ('contacted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='general.member')),
                ('managers', models.ManyToManyField(to='general.Member')),
                ('selected_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EPs', to='applications.program')),
            ],
        ),
    ]
