# Generated by Django 3.1.1 on 2020-10-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_ups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ep',
            options={'verbose_name': 'EP'},
        ),
    ]
