# Generated by Django 3.1.1 on 2021-03-13 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0006_auto_20201018_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OperationalFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_up', models.BooleanField(default=False)),
                ('applied', models.BooleanField(default=False)),
                ('accepted_by_host', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('realized', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('re_approved', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('contacted', models.BooleanField(default=False)),
                ('realization_broken', models.BooleanField(default=False)),
                ('approval_broken', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('withdrawn', models.BooleanField(default=False)),
                ('pending_enabler_acceptance', models.BooleanField(default=False)),
                ('out_of_process', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target', models.DecimalField(decimal_places=2, max_digits=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ir', models.BooleanField()),
                ('process_time_SU_APL', models.DurationField()),
                ('process_time_APL_ACC', models.DurationField()),
                ('process_time_APL_APD', models.DurationField()),
                ('process_time_SU_contacted', models.DurationField()),
                ('process_time_APL_contacted', models.DurationField()),
                ('notes', models.TextField()),
                ('applied_at', models.DateField()),
                ('accepted_at', models.DateField()),
                ('approved_at', models.DateField()),
                ('realized_at', models.DateField()),
                ('contract_price', models.IntegerField()),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications.accepted_by+', to='general.member')),
                ('application_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications.app_manager+', to='general.member')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications.approved_by+', to='general.member')),
                ('contacted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications.contacted_by+', to='general.member')),
                ('cv_filtered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications.cv_filterd_by+', to='general.member')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications.duration+', to='applications.duration')),
            ],
        ),
    ]
