# Generated by Django 3.1.1 on 2021-03-13 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('general', '0006_auto_20201018_0420'),
        ('sign_ups', '0001_initial'),
        ('opportunities', '0004_auto_20201018_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications.eb+', to='sign_ups.ep'),
        ),
        migrations.AddField(
            model_name='application',
            name='home_lc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications.home_lc+', to='general.entity'),
        ),
        migrations.AddField(
            model_name='application',
            name='home_mc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications.home_mc+', to='general.entity'),
        ),
        migrations.AddField(
            model_name='application',
            name='host_lc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications.host_lc+', to='general.entity'),
        ),
        migrations.AddField(
            model_name='application',
            name='host_mc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications.host_mc+', to='general.entity'),
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications.program+', to='applications.program'),
        ),
        migrations.AddField(
            model_name='application',
            name='re_approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications.reapproved_by+', to='general.member'),
        ),
        migrations.AddField(
            model_name='application',
            name='realized_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications.realized_by+', to='general.member'),
        ),
        migrations.AddField(
            model_name='application',
            name='sdg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications.sdg+', to='applications.sdg'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications.status+', to='applications.operationalflow'),
        ),
        migrations.AddField(
            model_name='application',
            name='sub_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications.sub_product+', to='applications.subproduct'),
        ),
        migrations.AddField(
            model_name='application',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications.tag+', to='general.tag'),
        ),
        migrations.AddField(
            model_name='application',
            name='tn_fees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications.tn_fees+', to='opportunities.opportunity'),
        ),
    ]
