# Generated by Django 3.1.1 on 2020-10-21 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0014_auto_20201021_2230'),
        ('applications', '0001_initial'),
        ('sign_ups', '0001_initial'),
        ('opportunities', '0006_auto_20201021_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_ep', to='sign_ups.ep'),
        ),
        migrations.AddField(
            model_name='application',
            name='home_lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_home_lc', to='general.entity'),
        ),
        migrations.AddField(
            model_name='application',
            name='home_mc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_home_mc', to='general.entity'),
        ),
        migrations.AddField(
            model_name='application',
            name='host_lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_host_lc', to='general.entity'),
        ),
        migrations.AddField(
            model_name='application',
            name='host_mc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_host_mc', to='general.entity'),
        ),
        migrations.AddField(
            model_name='application',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_product', to='applications.product'),
        ),
        migrations.AddField(
            model_name='application',
            name='re_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_re_approved_by', to='general.member'),
        ),
        migrations.AddField(
            model_name='application',
            name='realized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_realized_by', to='general.member'),
        ),
        migrations.AddField(
            model_name='application',
            name='sdg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_sdg', to='applications.sdg'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_status', to='applications.status'),
        ),
        migrations.AddField(
            model_name='application',
            name='sub_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_sub_product', to='applications.subproduct'),
        ),
        migrations.AddField(
            model_name='application',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_tags', to='general.tag'),
        ),
        migrations.AddField(
            model_name='application',
            name='tn_fees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_tn_fees', to='opportunities.opportunity'),
        ),
    ]
