# Generated by Django 3.1.1 on 2020-10-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20201021_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sdg',
            options={'verbose_name': 'SDG'},
        ),
    ]
