from django.contrib import admin
from general.models import *
from opportunities.models import *
from tm.models import *

# Register your models here.

admin.site.register(Entity)
admin.site.register(Member)
admin.site.register(Role)
admin.site.register(Skill)
admin.site.register(Language)
admin.site.register(Background)
admin.site.register(Department)
admin.site.register(Address)
admin.site.register(Tag)
admin.site.register(Opportunity)
admin.site.register(Slot)
admin.site.register(TouchPoints)
admin.site.register(OperationalGoal)
admin.site.register(Nes)
admin.site.register(Pipeline)
admin.site.register(TeamStandards)
admin.site.register(IndividualPlan)
admin.site.register(TeamCreation)
admin.site.register(TeamPlan)
admin.site.register(Building)
admin.site.register(Performing)
admin.site.register(Closing)
admin.site.register(SupportSystem)
admin.site.register(PerformanceTracking)
admin.site.register(ResultsEvaluation)
admin.site.register(Nps)
admin.site.register(Transition)
admin.site.register(IndividualTransition)
admin.site.register(TeamDebrief)
# admin.site.register()
# admin.site.register()
# admin.site.register()
# admin.site.register()
# admin.site.register()
