# Generated by Django 3.1.1 on 2020-10-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[(1, 'Active Member'), (2, 'Member on IXP'), (3, 'Resigned'), (4, 'Dismissed'), (5, 'Under Probation'), (6, 'Alumnus')], default='Active Member', max_length=1)),
            ],
        ),
    ]
