# Generated by Django 3.1.1 on 2020-10-18 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership_Status',
        ),
    ]
