# Generated by Django 3.1.1 on 2020-10-20 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0004_auto_20201019_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_lda', models.IntegerField(blank=True, default=0, null=True)),
                ('final_pdp', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nps', models.IntegerField(blank=True, default=0, null=True)),
                ('nps_explaination', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'NPS',
                'verbose_name_plural': 'NPS',
            },
        ),
        migrations.CreateModel(
            name='PerformanceTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountability_system', models.IntegerField(blank=True, default=0, null=True)),
                ('individual_tracking', models.IntegerField(blank=True, default=0, null=True)),
                ('team_reviews', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultsTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practical_learning', models.IntegerField(blank=True, default=0, null=True)),
                ('working_times', models.IntegerField(blank=True, default=0, null=True)),
                ('incentives', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_spaces', models.IntegerField(blank=True, default=0, null=True)),
                ('team_meetings', models.IntegerField(blank=True, default=0, null=True)),
                ('o2o', models.IntegerField(blank=True, default=0, null=True)),
                ('team_days', models.IntegerField(blank=True, default=0, null=True)),
                ('feedback', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamDebrief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting', models.IntegerField(blank=True, default=0, null=True)),
                ('team_development_review', models.IntegerField(blank=True, default=0, null=True)),
                ('feedback', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_and_skills', models.IntegerField(blank=True, default=0, null=True)),
                ('documents_and_tools', models.IntegerField(blank=True, default=0, null=True)),
                ('suggestions_of_way_forward', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='nes',
            name='nps_explaination',
        ),
        migrations.AlterField(
            model_name='individualplan',
            name='initial_lda',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='individualplan',
            name='pdp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teamcreation',
            name='competence',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teamcreation',
            name='team_rules',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teamcreation',
            name='transition',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teamplan',
            name='budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teamplan',
            name='goals',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teamplan',
            name='jds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teamplan',
            name='strategies',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teamplan',
            name='team_development',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teamplan',
            name='team_purpose',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teamplan',
            name='timeline',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Performing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_tracking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm.performancetracking')),
                ('results_elevation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm.resultstracking')),
                ('support_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm.supportsystem')),
            ],
        ),
        migrations.CreateModel(
            name='Closing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm.individualtransition')),
                ('team_debrief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm.teamdebrief')),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm.transition')),
            ],
        ),
        migrations.AddField(
            model_name='teamstandards',
            name='closing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm.closing'),
        ),
        migrations.AddField(
            model_name='teamstandards',
            name='performing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm.performing'),
        ),
        migrations.AlterField(
            model_name='nes',
            name='nps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm.nps'),
        ),
    ]
