# Generated by Django 3.1.1 on 2020-10-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0005_auto_20201020_0238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResultsTracking',
            new_name='ResultsEvaluation',
        ),
        migrations.AlterField(
            model_name='nps',
            name='nps',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
