# Generated by Django 3.1.1 on 2020-10-21 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_auto_20201021_2230'),
        ('tm', '0006_auto_20201020_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='individual_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_individual_plan', to='tm.individualplan'),
        ),
        migrations.AlterField(
            model_name='building',
            name='team_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_creation', to='tm.teamcreation'),
        ),
        migrations.AlterField(
            model_name='building',
            name='team_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_team_plan', to='tm.teamplan'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='individual_transition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closing_ind_transition', to='tm.individualtransition'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='team_debrief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closing_debrief', to='tm.teamdebrief'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='transition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closing_transition', to='tm.transition'),
        ),
        migrations.AlterField(
            model_name='nes',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nes_department', to='general.department'),
        ),
        migrations.AlterField(
            model_name='nes',
            name='lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nes_lc', to='general.entity'),
        ),
        migrations.AlterField(
            model_name='nes',
            name='member_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nes_member_name', to='general.member'),
        ),
        migrations.AlterField(
            model_name='nes',
            name='nps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nes_nps', to='tm.nps'),
        ),
        migrations.AlterField(
            model_name='nes',
            name='percentage_of_goal_achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nes_goal_ach', to='tm.plannedvsachieved'),
        ),
        migrations.AlterField(
            model_name='nes',
            name='pipeline',
            field=models.ManyToManyField(blank=True, default=0, null=True, related_name='nes_pipeline', to='tm.Pipeline'),
        ),
        migrations.AlterField(
            model_name='nes',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nes_role', to='general.role'),
        ),
        migrations.AlterField(
            model_name='nes',
            name='team_standards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nes_ts', to='tm.teamstandards'),
        ),
        migrations.AlterField(
            model_name='performing',
            name='performance_tracking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performing_tracking', to='tm.performancetracking'),
        ),
        migrations.AlterField(
            model_name='performing',
            name='results_elevation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performing_result', to='tm.resultsevaluation'),
        ),
        migrations.AlterField(
            model_name='performing',
            name='support_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performing_support_system', to='tm.supportsystem'),
        ),
        migrations.AlterField(
            model_name='plannedvsachieved',
            name='planned',
            field=models.ManyToManyField(blank=True, null=True, related_name='PvsA', to='general.OperationalGoal'),
        ),
        migrations.AlterField(
            model_name='teamstandards',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building', to='tm.building'),
        ),
        migrations.AlterField(
            model_name='teamstandards',
            name='closing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closing', to='tm.closing'),
        ),
        migrations.AlterField(
            model_name='teamstandards',
            name='performing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performing', to='tm.performing'),
        ),
    ]
