# Generated by Django 3.1.1 on 2020-10-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='tags',
            field=models.ManyToManyField(to='general.Tag'),
        ),
        migrations.DeleteModel(
            name='TagCount',
        ),
    ]
