# Generated by Django 3.1.1 on 2020-10-16 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20201016_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_count',
        ),
        migrations.AlterField(
            model_name='background',
            name='expa_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='expa_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='expa_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='atom_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='backgrounds',
            field=models.ManyToManyField(blank=True, null=True, to='general.Background'),
        ),
        migrations.AlterField(
            model_name='member',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='user-cv/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.department'),
        ),
        migrations.AlterField(
            model_name='member',
            name='expa_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='general.Language'),
        ),
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user-images/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.role'),
        ),
        migrations.AlterField(
            model_name='member',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='general.Skill'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='general.Tag'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='expa_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
