# Generated by Django 3.1.1 on 2020-10-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20201016_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
