# Generated by Django 3.1.1 on 2020-10-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_member_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='managed_applcations_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='managed_enablers_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='managed_eps_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='managed_opportunities_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
