# Generated by Django 3.1.1 on 2020-10-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
        ('general', '0005_auto_20201018_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='managed_ops',
            field=models.ManyToManyField(blank=True, null=True, to='opportunities.Opportunity'),
        ),
        migrations.AddField(
            model_name='member',
            name='managed_partners_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
