# Generated by Django 3.1.1 on 2020-10-18 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20201018_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'Active Member'), (2, 'Member on IXP'), (3, 'Resigned'), (4, 'Dismissed'), (5, 'Under Probation'), (6, 'Alumnus')], default='Active Member', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='completed_one_membership_cycle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_cycles',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='ReasonOfLeaving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_of_leaving', models.TextField(blank=True, null=True)),
                ('status', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.membershipstatus')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='membership_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.reasonofleaving'),
        ),
    ]
