# Generated by Django 3.1.1 on 2020-10-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20201018_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reasonofleaving',
            name='status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_status',
        ),
        migrations.AddField(
            model_name='member',
            name='member_status',
            field=models.CharField(choices=[(1, 'Active Member'), (2, 'Member on IXP'), (3, 'Resigned'), (4, 'Dismissed'), (5, 'Under Probation'), (6, 'Alumnus')], default='Active Member', max_length=1),
        ),
        migrations.AddField(
            model_name='member',
            name='reason_of_leaving',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MembershipStatus',
        ),
        migrations.DeleteModel(
            name='ReasonOfLeaving',
        ),
    ]
