# Generated by Django 3.1.1 on 2020-10-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_auto_20201019_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalgoal',
            name='goal',
            field=models.CharField(choices=[('SU', 'Sign UPs'), ('APL', 'Applied'), ('ACC', 'Accepted'), ('APD', 'Approved'), ('RE', 'Realized'), ('FI', 'Finished'), ('CO', 'Complete'), ('XX', 'Choose a type')], default='XX', max_length=3),
        ),
    ]
