# Generated by Django 3.1.1 on 2020-10-20 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0006_auto_20201020_0250'),
        ('general', '0012_auto_20201020_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='members_nps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tm.nps'),
        ),
        migrations.AlterField(
            model_name='member',
            name='reason_of_leaving',
            field=models.CharField(blank=True, choices=[('1', 'Own Decision'), ('2', 'Low Performance'), ('3', 'Low engagement'), ('4', 'Unethical Behavior'), ('5', 'Rules Violation'), ('6', 'Other')], default='Other', max_length=1, null=True),
        ),
    ]
