# Generated by Django 3.1.1 on 2020-10-21 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_auto_20201021_2230'),
        ('general', '0014_auto_20201021_2230'),
        ('sign_ups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tm', '0007_auto_20201021_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='managed_eps',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_managed_eps', to='sign_ups.EP'),
        ),
        migrations.AddField(
            model_name='member',
            name='operational_status',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_operational_status', to='sign_ups.EP'),
        ),
        migrations.AddField(
            model_name='member',
            name='touch_points',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_touch_points', to='general.touchpoints'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_parent', to='general.entity'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_address', to='general.address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='backgrounds',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_backgrounds', to='general.Background'),
        ),
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_department', to='general.department'),
        ),
        migrations.AlterField(
            model_name='member',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_languages', to='general.Language'),
        ),
        migrations.AlterField(
            model_name='member',
            name='lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_lc', to='general.entity'),
        ),
        migrations.AlterField(
            model_name='member',
            name='managed_ops',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_managed_ops', to='opportunities.Opportunity'),
        ),
        migrations.AlterField(
            model_name='member',
            name='members_nps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_nps', to='tm.nps'),
        ),
        migrations.AlterField(
            model_name='member',
            name='operational_goals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_operational_goals', to='general.operationalgoal'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_roles', to='general.Role'),
        ),
        migrations.AlterField(
            model_name='member',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_skills', to='general.Skill'),
        ),
        migrations.AlterField(
            model_name='member',
            name='team_standards',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_ts', to='tm.TeamStandards'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_department', to='general.department'),
        ),
        migrations.AlterField(
            model_name='role',
            name='lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_lc', to='general.entity'),
        ),
        migrations.AlterField(
            model_name='touchpoints',
            name='audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_audience', to='general.role'),
        ),
        migrations.AlterField(
            model_name='touchpoints',
            name='meeting_host_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_entity', to='general.entity'),
        ),
        migrations.AlterField(
            model_name='touchpoints',
            name='meeting_type',
            field=models.CharField(choices=[('1', 'National Conference'), ('2', 'Local Conference'), ('3', 'LCM'), ('4', 'MCM'), ('5', 'Comission Meeting'), ('6', 'Functional Visit'), ('7', 'OD Visit'), ('8', 'o2o'), ('9', 'Commission Meeting'), ('10', 'Functional Meeting'), ('11', 'TLs Meeting'), ('12', 'EB Meeting'), ('13', 'Management Team Meeting'), ('14', 'OD Meeting'), ('15', 'OPS Meeting'), ('16', 'Brand Meeting'), ('17', 'Finance Meeting'), ('18', 'EDTs Meeting'), ('19', 'IR Meeting'), ('20', 'LC Outing'), ('21', 'Team days'), ('XX', 'Other')], default='Other', max_length=2),
        ),
    ]
