# Generated by Django 3.1.1 on 2020-10-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0005_auto_20201018_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.IntegerField(blank=True, default=0, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('application_close', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_id', models.IntegerField(blank=True, default=0, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('applicants_count', models.IntegerField(null=True)),
                ('enabler', models.CharField(max_length=200, null=True)),
                ('lc', models.CharField(max_length=100, null=True)),
                ('mc', models.CharField(max_length=100, null=True)),
                ('tn_fees', models.IntegerField(default=0, null=True)),
                ('sdg', models.CharField(max_length=200, null=True)),
                ('sub_product', models.CharField(max_length=200, null=True)),
                ('op_manager', models.ManyToManyField(blank=True, null=True, to='general.Member')),
                ('slot', models.ManyToManyField(blank=True, null=True, to='opportunities.Slot')),
            ],
        ),
    ]
