# Generated by Django 3.1.1 on 2020-10-18 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_auto_20201018_0423'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slot',
            new_name='Slots',
        ),
    ]
