# Generated by Django 3.1.1 on 2020-10-18 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_auto_20201018_0424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slots',
            new_name='Slot',
        ),
    ]
