# Generated by Django 3.1.1 on 2020-10-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_auto_20201018_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='op_manager',
            new_name='op_managers',
        ),
    ]
