# Generated by Django 3.1.1 on 2020-10-21 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_auto_20201021_2230'),
        ('opportunities', '0005_auto_20201019_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='tn_fees',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='op_status',
            field=models.CharField(blank=True, choices=[('1', 'Draft'), ('2', 'Under Review'), ('3', 'Live'), ('4', 'Unpublished'), ('5', 'Expired')], default='Draft', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_lc', to='general.entity'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='mc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_mc', to='general.entity'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='op_managers',
            field=models.ManyToManyField(blank=True, null=True, related_name='opportunity_managers', to='general.Member'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='slot',
            field=models.ManyToManyField(blank=True, null=True, related_name='opportunity_slots', to='opportunities.Slot'),
        ),
    ]
